---

- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    - slurm-master


- name: Slurm worker nodes Playbook
  hosts: slurm_worker
  roles:
    - slurm-worker


- name: Slurm submit nodes Playbook
  hosts: slurm_submit:slurm_client
  roles:
    - slurm-client


- name: Restart SLURMd after all config is done
  hosts: slurm_worker
  tasks:
    - service:
        name=slurmd
        state=restarted
      when: '{{is_debian_compatible}} and ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'
    - service:
        name=slurm-llnl
        state=restarted
      when: '{{is_debian_compatible}} and (not ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}}))'
    - service:
        name=slurmd
        state=restarted
      when: '{{is_rhel7_compatible}}'
    - service:
        name=slurm
        state=restarted
      when: '{{is_rhel6_compatible}}'